### ISSUE TITLE
Error while retrieving headers with BatchEnricher

### ISSUE THREAD

**Issue by boogheta** [medialab/casanova#123]
When using --resume on a minet twitter friends command with casanova 1.11.1 (minet 1.0.0-a33), casanova breaks while trying to retrieve headers:

```
Traceback (most recent call last):
  File "/home/benjamin.ooghe/.pyenv/versions/minet/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/__main__.py", line 14, in main
    run("minet", __identifier__, MINET_COMMANDS)
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/utils.py", line 49, in wrapper
    fn(*args, **kwargs)
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/run.py", line 119, in run
    fn(cli_args)
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/utils.py", line 399, in wrapper
    enricher = enricher_fn(
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/casanova/enricher.py", line 250, in __init__
    super().__init__(input_file, output_file, add=add, **kwargs)
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/casanova/enricher.py", line 99, in __init__
    self.resumer.get_insights_from_output(
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/casanova/resumers.py", line 211, in get_insights_from_output
    self.value_pos = enricher.output_headers[self.value_column]
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/casanova/enricher.py", line 137, in output_headers
    return self.writer.headers
AttributeError: 'BatchEnricher' object has no attribute 'writer'
```

It looks to me like this could be fixed by [giving self.headers instead of self.writer.headers on this line](https://github.com/medialab/casanova/blob/master/casanova/enricher.py#L137), but when doing this I encounter another error from the twitter lib that seems to indicate the headers given are not the good one?

```
minet process was stopped because an error occurred!
Traceback (most recent call last):
  File "/home/benjamin.ooghe/.pyenv/versions/minet/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/__main__.py", line 14, in main
    run("minet", __identifier__, MINET_COMMANDS)
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/utils.py", line 49, in wrapper
    fn(*args, **kwargs)
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/run.py", line 119, in run
    fn(cli_args)
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/utils.py", line 427, in wrapper
    return action(cli_args, *args, **additional_kwargs, **kwargs)
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/twitter/utils.py", line 51, in wrapper
    return action(cli_args, *args, **{"client": client}, **kwargs)
  File "/home/benjamin.ooghe/.pyenv/versions/3.9.13/envs/minet/lib/python3.9/site-packages/minet/cli/twitter/utils.py", line 84, in action
    next_cursor = int(resuming_state.last_cursor)
ValueError: invalid literal for int() with base 10: 'SKKCBJNM8A31AZZZ'
```

**Comment by boogheta** [comment]
hint from @Yomguithereal : hotfixing should rather be using `enricher.writer.headers` in  https://github.com/medialab/casanova/blob/master/casanova/resumers.py#L211 en
