### ISSUE TITLE
Weird escapechar error

### ISSUE THREAD

**Issue by boogheta** [medialab/casanova#65]
when running minet tweet search and reaching a [specific guilty tweet](https://twitter.com/jengonsoyyo1/status/1007864969373913088), we encounter a surprising casanova error reported by the python csv native library:

`minet twitter tweet-search --rcfile twitterv2_keys.yml -o /tmp/culprit.csv --academic "youtube.com/watch?v=OMOGaugKpzs" --until-id 1007867183240699904`

```
Retrieving tweets: 106416 tweets [54:13, 71.28 tweets/s, queries=85]
Traceback (most recent call last):
  File "/home/kelly.christensen/.pyenv/versions/medias/bin/minet", line 33, in <module>
    sys.exit(load_entry_point('minet==0.63.1', 'console_scripts', 'minet')())
  File "/home/kelly.christensen/.pyenv/versions/3.10.6/envs/medias/lib/python3.10/site-packages/minet/cli/__main__.py", line 215, in main
    fn(cli_args)
  File "/home/kelly.christensen/.pyenv/versions/3.10.6/envs/medias/lib/python3.10/site-packages/minet/cli/twitter/__init__.py", line 68, in twitter_action
    twitter_tweet_search_action(cli_args)
  File "/home/kelly.christensen/.pyenv/versions/3.10.6/envs/medias/lib/python3.10/site-packages/minet/cli/twitter/tweet_search.py", line 94, in twitter_tweet_search_action
    enricher.writerow(row, addendum)
  File "/home/kelly.christensen/.pyenv/versions/3.10.6/envs/medias/lib/python3.10/site-packages/casanova/enricher.py", line 129, in writerow
    self.writer.writerow(self.formatrow(row, add))
_csv.Error: need to escape, but no escapechar set
```

We can solve it by forcing csv.writer to use an escape character [here](https://github.com/medialab/casanova/blob/master/casanova/enricher.py#L83) by adding for instance `, escapechar='\\'`, although it works whatever the escape character given and the resulting line does not contain it whatsoever.
This is especially surprising since according to the [API doc](https://docs.python.org/3/library/csv.html#dialects-and-formatting-parameters), escapechar is only required if quoting is set to QUOTE_NONE (which is not the case here) or doublequote is set to False, whereas it's set to True by default and is not specified here. So I don't really understand how this can happen...

 (python 3.10.6 used in the tests)

**Comment by Yomguithereal** [comment]
Plan to "fix" this, or at least alleviate the issue:

- [ ] drop the namedtuple polyfill and drop support for 3.6
- [ ] if py >= 3.10 & if writer dialect has no escapechar set, wrap writerow in try catch and rewrite null byte in output

**Comment by Yomguithereal** [comment]
I think we need to have a kwarg to filter out null bytes on write. This may need to rewrite the reader kwarg for clarity.
